from jinja2 import Template
TEMPLATE = """
<!DOCTYPE html><html lang="ja"><head><meta charset="utf-8" />
<title>{{ title }}</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Hiragino Sans","Noto Sans JP","Yu Gothic","Helvetica Neue",Arial,sans-serif;line-height:1.6;padding:24px;color:#111;}
h1,h2{margin:.4em 0;} table{border-collapse:collapse;width:100%;margin:12px 0 24px;}
th,td{border:1px solid #ddd;padding:8px 10px;text-align:left;font-size:14px;} th{background:#f5f5f7;}
.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:12px;background:#eef;}
.code{font-family:ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono","Courier New", monospace;}
small{color:#666;}
</style></head><body>
<h1>{{ title }}</h1>
<p><span class="badge">Audio MVP</span> 9分窓 × Diarization × ASR × Prosody</p>
<h2>1) セッション表（segments）</h2>
<table><thead><tr><th>#</th><th>start</th><th>end</th><th>speaker</th><th>text</th></tr></thead><tbody>
{% for row in segments %}
<tr><td>{{ loop.index }}</td><td>{{ "%.2f"|format(row.start) }}</td><td>{{ "%.2f"|format(row.end) }}</td><td>{{ row.speaker }}</td><td>{{ row.text }}</td></tr>
{% endfor %}
</tbody></table>
<h2>2) 記述統計（turns）</h2>
<table><thead><tr><th>role</th><th>n_utts</th><th>n_tokens</th><th>n_types</th><th>mlu</th><th>mean_turn_len</th><th>turn_latency_mean</th></tr></thead><tbody>
{% for row in turns %}
<tr><td>{{ row.role }}</td><td>{{ row.n_utts }}</td><td>{{ row.n_tokens }}</td><td>{{ row.n_types }}</td><td>{{ "%.2f"|format(row.mlu) }}</td><td>{{ "%.2f"|format(row.mean_turn_len) }}</td><td>{{ "%.2f"|format(row.turn_latency_mean) }}</td></tr>
{% endfor %}
</tbody></table>
<h2>3) 韻律（prosody）</h2>
<table><thead><tr><th>role</th><th>f0_mean</th><th>f0_sd</th><th>energy_mean</th><th>speech_rate</th><th>pause_p95</th></tr></thead><tbody>
{% for row in prosody %}
<tr><td>{{ row.role }}</td><td>{{ "%.1f"|format(row.f0_mean) }}</td><td>{{ "%.1f"|format(row.f0_sd) }}</td><td>{{ "%.4f"|format(row.energy_mean) }}</td><td>{{ "%.2f"|format(row.speech_rate) }}</td><td>{{ "%.2f"|format(row.pause_p95) }}</td></tr>
{% endfor %}
</tbody></table>
<h2>4) 語用論（pragmatics）</h2>
<table><thead><tr><th>role</th><th>question_rate</th><th>dm/100t</th><th>mental/100t</th></tr></thead><tbody>
{% for row in pragmatics %}
<tr><td>{{ row.role }}</td><td>{{ "%.2f"|format(row.question_rate) }}</td><td>{{ "%.2f"|format(row.dm_per_100t) }}</td><td>{{ "%.2f"|format(row.mental_per_100t) }}</td></tr>
{% endfor %}
</tbody></table>
<p class="code"><small>Generated by audio_mvp</small></p>
</body></html>
"""
def render_html(title, segments, turns, prosody, pragmatics):
    return Template(TEMPLATE).render(title=title, segments=segments, turns=turns, prosody=prosody, pragmatics=pragmatics)
